# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [0]:
%tensorflow_version 2.x

TensorFlow 2.x selected.


### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [0]:
import tensorflow as tf
print(tf.__version__)

2.1.0-rc1


### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [0]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris

iris_df = load_iris()
iris_df

{'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ===========

## Question 2

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

In [0]:
data = iris_df.data
target= iris_df.target

## Question 3

### Create train and test data
- use train_test_split to get train and test set
- set a random_state
- test_size: 0.25

In [0]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data, target, test_size= 0.25, random_state= 42)

## Question 4

### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [0]:
# OneHotEncoding of Train & Test Class Variables using Keras.
from keras.utils import to_categorical

y_train_binary = to_categorical(y_train, num_classes= 3,  dtype= 'int32')
y_train_binary

Using TensorFlow backend.


array([[1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0,

In [0]:
y_test_binary = to_categorical(y_test, num_classes= 3, dtype= 'int32')
y_test_binary

array([[0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0]], dtype=int32)

## Question 5

### Initialize a sequential model
- Define a sequential model

In [0]:
from tensorflow.python.keras.layers import Dense

from tensorflow.python.keras import Sequential

# Initialize the constructor
model = Sequential()

## Question 6

### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [0]:
# Adding and input layer with 4 input shape

model.add(Dense(5, activation= 'softmax', input_shape=(4,)))

# Adding an output layer with 3 output shape with Softmax

model.add(Dense(3, activation='softmax'))

## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [0]:
model.compile(loss='categorical_crossentropy',
              optimizer='SGD',
              metrics=['accuracy'])

## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [0]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 5)                 25        
_________________________________________________________________
dense_1 (Dense)              (None, 3)                 18        
Total params: 43
Trainable params: 43
Non-trainable params: 0
_________________________________________________________________


## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [0]:
history = model.fit(X_train, y_train_binary,epochs=100, batch_size=1, verbose=1)

Train on 112 samples
Epoch 1/100
112/112 [==============================] - 0s 3ms/sample - loss: 1.0599 - accuracy: 0.3839
Epoch 2/100
112/112 [==============================] - 0s 1ms/sample - loss: 0.9147 - accuracy: 0.7054
Epoch 3/100
112/112 [==============================] - 0s 1ms/sample - loss: 0.8334 - accuracy: 0.6696
Epoch 4/100
112/112 [==============================] - 0s 1ms/sample - loss: 0.7766 - accuracy: 0.7500
Epoch 5/100
112/112 [==============================] - 0s 1ms/sample - loss: 0.7322 - accuracy: 0.7589
Epoch 6/100
112/112 [==============================] - 0s 1ms/sample - loss: 0.6992 - accuracy: 0.6786
Epoch 7/100
112/112 [==============================] - 0s 1ms/sample - loss: 0.6715 - accuracy: 0.6964
Epoch 8/100
112/112 [==============================] - 0s 1ms/sample - loss: 0.6498 - accuracy: 0.7500
Epoch 9/100
112/112 [==============================] - 0s 1ms/sample - loss: 0.6315 - accuracy: 0.7143
Epoch 10/100
112/112 [==============================

## Question 10

### Make predictions
- Predict labels on one row

In [0]:
y_pred = np.round(model.predict(X_test))
y_pred[0:10]

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.]], dtype=float32)

### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

In [0]:
score = model.evaluate(X_test, y_test_binary,verbose=1)

print(score)

38/38 [==============================] - 0s 2ms/sample - loss: 0.3095 - accuracy: 0.8947
[0.30946494403638336, 0.8947368]




---



# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [1]:
%tensorflow_version 2.x

TensorFlow 2.x selected.


### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [2]:
import tensorflow as tf
print(tf.__version__)

2.1.0-rc1


### Set random seed

In [0]:
tf.random.set_seed(42)

In [0]:
!pip install pyDrive

In [0]:
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

In [0]:
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [0]:
downloaded = drive.CreateFile({'id':"17KO_FB38OaByOtu4r6dxbzAlBa2VHb7R"})
downloaded.GetContentFile('prices.csv')

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

In [8]:
import pandas as pd
data = pd.read_csv('prices.csv')
data.head()

date symbol        open  ...         low        high     volume
0  2016-01-05 00:00:00   WLTW  123.430000  ...  122.309998  126.250000  2163600.0
1  2016-01-06 00:00:00   WLTW  125.239998  ...  119.940002  125.540001  2386400.0
2  2016-01-07 00:00:00   WLTW  116.379997  ...  114.930000  119.739998  2489500.0
3  2016-01-08 00:00:00   WLTW  115.480003  ...  113.500000  117.440002  2006300.0
4  2016-01-11 00:00:00   WLTW  117.010002  ...  114.089996  117.330002  1408600.0

[5 rows x 7 columns]

In [9]:
data.describe().transpose()

count          mean  ...           75%           max
open    851264.0  7.083699e+01  ...  7.988000e+01  1.584440e+03
close   851264.0  7.085711e+01  ...  7.989000e+01  1.578130e+03
low     851264.0  7.011841e+01  ...  7.911000e+01  1.549940e+03
high    851264.0  7.154348e+01  ...  8.061000e+01  1.600930e+03
volume  851264.0  5.415113e+06  ...  5.222500e+06  8.596434e+08

[5 rows x 8 columns]

In [0]:
data.isna().sum()

date      0
symbol    0
open      0
close     0
low       0
high      0
volume    0
dtype: int64

## Question 2

### Drop columnns
- drop "date" and "symbol" column from the data

In [0]:
data = data.drop(['date', 'symbol'], axis = 1)

In [0]:
data.dtypes

open      float64
close     float64
low       float64
high      float64
volume    float64
dtype: object

## Question 3

### Take initial rows
- Take first 1000 rows from the data
- This step is done to make the execution faster

In [0]:
#Get first 1000 rows
data_df = data.head(1000)

In [0]:
data_df.shape

(1000, 5)

## Question 4

### Get features and label from the dataset in separate variable
- Take "open", "close", "low", "high" columns as features
- Take "volume" column as label
- Normalize label column by dividing it with 1000000

In [0]:
X = data_df.drop(['volume'], axis = 1) # this will internally select open, close, low & high features.
y = (data_df['volume']/1000000)

In [0]:
from sklearn.model_selection import train_test_split

X_train_stock, X_test_stock, y_train_stock, y_test_stock = train_test_split(X, y, test_size= 0.7, random_state= 41)

## Question 5

### Convert data
- Convert features and labels to numpy array
- Convert their data type to "float32"

In [0]:
X_numpy = X.to_numpy(dtype='float32')
y_numpy = y.to_numpy(dtype='float32')

In [0]:
X_numpy.shape

(1000, 4)

In [0]:
y_numpy.shape

(1000,)

## Question 6

### Normalize data
- Normalize features
- Use tf.math.l2_normalize to normalize features
- You can read more about it here https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize

In [0]:
X_norm_tensor = tf.math.l2_normalize(X_numpy)

In [0]:
X_norm_tensor

<tf.Tensor: shape=(1000, 4), dtype=float32, numpy=
array([[0.02202894, 0.02245906, 0.02182905, 0.02253223],
       [0.02235197, 0.02141321, 0.02140607, 0.02240551],
       [0.0207707 , 0.02051548, 0.02051192, 0.02137037],
       ...,
       [0.00505436, 0.00513467, 0.00499903, 0.00514181],
       [0.00785282, 0.0079956 , 0.0078082 , 0.00799738],
       [0.00643931, 0.00662849, 0.00642682, 0.00664455]], dtype=float32)>

## Question 7

### Define weight and bias
- Initialize weight and bias with tf.zeros
- tf.zeros is an initializer that generates tensors initialized to 0
- Specify the value for shape

In [0]:
weights = tf.zeros((4, 1), dtype=tf.dtypes.float32)

In [0]:
weights

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[0.],
       [0.],
       [0.],
       [0.]], dtype=float32)>

In [0]:
bias = tf.zeros(shape= (1000, 1), dtype=tf.dtypes.float32)

In [0]:
bias

<tf.Tensor: shape=(1000, 1), dtype=float32, numpy=
array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],


## Question 8

### Get prediction
- Define a function to get prediction
- Approach: prediction = (X * W) + b; here is X is features

In [0]:
def get_prediction(X, W, b):
  return tf.add(tf.multiply(X, W), b)

In [0]:
learning_rate = 0.01
training_epochs = 100

In [0]:
y_pred = tf.add(tf.matmul(X_norm_tensor, weights), bias) # Equivalent to get_prediction method.

In [0]:
y_pred

<tf.Tensor: shape=(1000, 1), dtype=float32, numpy=
array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],


### Calculate loss
- Calculate loss using predictions
- Define a function to calculate loss
- We are calculating mean squared error

In [0]:
# Mean Squared Error Cost Function
cost = tf.losses.mean_squared_error(y_numpy, y_pred)

## Question 9

### Define a function to train the model
1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [0]:
# Gradient Descent Optimizer 
optimizer = tf.compat.v1.train.GradientDescentOptimizer(learning_rate)
  
# Global Variables Initializer 
init = tf.compat.v1.global_variables_initializer()

## Question 10

### Train the model for 100 epochs 
- Observe the training loss at every iteration

In [0]:
from tensorflow.python.keras.layers import Dense

from tensorflow.python.keras import Sequential

def build_model():
  model = Sequential([
    Dense(64, activation='relu', input_shape=[len(X_train_stock.keys())]),
    Dense(64, activation='relu'),
    Dense(1)
  ])

  model.compile(loss='mse',
                optimizer=optimizer,
                metrics=['mae', 'mse'])
  return model

In [0]:
model = build_model()

In [31]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 64)                320       
_________________________________________________________________
dense_4 (Dense)              (None, 64)                4160      
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 65        
Total params: 4,545
Trainable params: 4,545
Non-trainable params: 0
_________________________________________________________________


In [32]:
history = model.fit(X_train_stock, y_train_stock, epochs=100, batch_size=1, verbose=1)

Train on 300 samples
Epoch 1/100
300/300 [==============================] - 1s 2ms/sample - loss: 121298379789051328.0000 - mae: 39963616.0000 - mse: 121298311754809344.0000
Epoch 2/100
300/300 [==============================] - 0s 1ms/sample - loss: 7756063420.2035 - mae: 50473.5977 - mse: 7756061696.0000
Epoch 3/100
300/300 [==============================] - 0s 1ms/sample - loss: 42147.6041 - mae: 118.3012 - mse: 42147.6016
Epoch 4/100
300/300 [==============================] - 0s 1ms/sample - loss: 55.4027 - mae: 3.6032 - mse: 55.4027
Epoch 5/100
300/300 [==============================] - 0s 1ms/sample - loss: 55.8382 - mae: 3.6160 - mse: 55.8382
Epoch 6/100
300/300 [==============================] - 0s 1ms/sample - loss: 55.6932 - mae: 3.6329 - mse: 55.6932
Epoch 7/100
300/300 [==============================] - 0s 1ms/sample - loss: 55.9801 - mae: 3.5623 - mse: 55.9801
Epoch 8/100
300/300 [==============================] - 0s 1ms/sample - loss: 55.8673 - mae: 3.6256 - mse: 55.8672


In [34]:
score = model.evaluate(X_test_stock, y_test_stock,verbose=1)

print(score)

700/700 [==============================] - 0s 150us/sample - loss: 281.5747 - mae: 5.0777 - mse: 281.5747
[281.5746840994699, 5.077669, 281.57468]


### Observe values of Weight
- Print the updated values

### Observe values of Bias
- Print the updated values